services:

  backend:

    image: ai-backend

    build:
      context: ./backend

    container_name: ai-backend

    ports:
      - "8000:8000"

    restart: unless-stopped

  frontend:

    image: ai-frontend

    build:
      context: ./frontend

    container_name: ai-frontend

    ports:
      - "3000:80"

    depends_on:
      - backend

    restart: unless-stopped